version: '2'

services:
  postgres:
    image: postgres

  ezbk:
    build: ./
    links:
      - postgres
    command: bundle exec thin -p 3000 start
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
